# Sustainability Analysis

### This project analyzes the data related to the United Nation's Global Sustainable Development Goal 12: "Ensure sustainable consumption and production patterns," in order to visualize trends and predict if the targets will be met by the goal target's deadlines.

### Goal and targets are as followed:

GOAL 12
  Ensure sustainable consumption and production patterns

TARGET 12.1
  Implement the 10-Year Framework of Programmes on Sustainable Consumption and Production Patterns, all countries taking action, with developed countries taking the lead, taking into account the development and capabilities of developing countries

TARGET 12.2
  By 2030, achieve the sustainable management and efficient use of natural resources

TARGET 12.3
  By 2030, halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains, including post-harvest losses

TARGET 12.4
  By 2020, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, in accordance with agreed international frameworks, and significantly reduce their release to air, water and soil in order to minimize their adverse impacts on human health and the environment

TARGET 12.c
  Rationalize inefficient fossil-fuel subsidies that encourage wasteful consumption by removing market distortions, in accordance with national circumstances, including by restructuring taxation and phasing out those harmful subsidies, where they exist, to reflect their environmental impacts, taking fully into account the specific needs and conditions of developing countries and minimizing the possible adverse impacts on their development in a manner that protects the poor and the affected communities

TARGET 12.b
  Develop and implement tools to monitor sustainable development impacts for sustainable tourism that creates jobs and promotes local culture and products


Imported xlsx files and information on goal 12 are from the UN's SDG database website: https://unstats.un.org/sdgs/indicators/database

# Import Dependencies

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import seaborn as sns
import os

# Read in xlsx files related to UN's Goal of Sustainability

## Electronic Waste Datasets

In [3]:
# 1st CSV
e_waste_pc = pd.read_excel('data/EN_EWT_GENPCAP.xlsx')
e_waste_pc.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Units,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,12,12.4,12.4.2,EN_EWT_GENPCAP,"Electronic waste generated, per capita (Kg)",4,Afghanistan,E,G,KG,...,0.254903,0.297841,0.342332,0.385085,0.427947,0.468858,0.509681,0.549503,0.592546,0.630326
1,12,12.4,12.4.2,EN_EWT_GENPCAP,"Electronic waste generated, per capita (Kg)",2,Africa,E,G,KG,...,1.736518,1.882356,1.991023,2.095194,2.187254,2.262542,2.333871,2.384393,2.438595,2.486051
2,12,12.4,12.4.2,EN_EWT_GENPCAP,"Electronic waste generated, per capita (Kg)",8,Albania,E,G,KG,...,4.391893,4.857921,5.310308,5.740930,6.112550,6.451386,6.736817,6.994344,7.225346,7.445564
3,12,12.4,12.4.2,EN_EWT_GENPCAP,"Electronic waste generated, per capita (Kg)",12,Algeria,E,G,KG,...,5.458888,5.745398,6.003581,6.236127,6.437032,6.603128,6.749312,6.874345,6.990501,7.106677
4,12,12.4,12.4.2,EN_EWT_GENPCAP,"Electronic waste generated, per capita (Kg)",19,Americas,E,G,KG,...,10.516785,10.952408,11.397137,11.812324,12.171035,12.470706,12.712160,12.926896,13.125069,13.310110

In [4]:
# 2nd CSV
e_waste_total = pd.read_excel('data/EN_EWT_GENV.xlsx')
e_waste_total.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Units,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,12,12.4,12.4.2,EN_EWT_GENV,Electronic waste generated (Tonnes),4,Afghanistan,E,G,TONNES,...,7.341974e+03,8.848573e+03,1.050856e+04,1.221951e+04,1.401868e+04,1.581739e+04,1.766350e+04,1.952385e+04,2.134352e+04,2.301319e+04
1,12,12.4,12.4.2,EN_EWT_GENV,Electronic waste generated (Tonnes),2,Africa,E,G,TONNES,...,1.623176e+06,1.783923e+06,1.943366e+06,2.097974e+06,2.244913e+06,2.382539e+06,2.515126e+06,2.649666e+06,2.780043e+06,2.905206e+06
2,12,12.4,12.4.2,EN_EWT_GENV,Electronic waste generated (Tonnes),8,Albania,E,G,TONNES,...,1.279358e+04,1.411226e+04,1.539989e+04,1.661999e+04,1.765916e+04,1.858644e+04,1.937509e+04,2.011573e+04,2.076565e+04,2.136877e+04
3,12,12.4,12.4.2,EN_EWT_GENV,Electronic waste generated (Tonnes),12,Algeria,E,G,TONNES,...,1.963999e+05,2.109538e+05,2.251043e+05,2.388250e+05,2.517781e+05,2.638808e+05,2.756149e+05,2.868045e+05,2.976695e+05,3.086217e+05
4,12,12.4,12.4.2,EN_EWT_GENV,Electronic waste generated (Tonnes),19,Americas,E,G,TONNES,...,9.557915e+06,1.004894e+07,1.055724e+07,1.104504e+07,1.148990e+07,1.188481e+07,1.222772e+07,1.254373e+07,1.283545e+07,1.312020e+07

## Electronic Waste Recycling Datasets

In [5]:
# 3rd CSV
e_recycling_pc = pd.read_excel('data/EN_EWT_RCYPCAP.xlsx')
e_recycling_pc.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Units,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,12,12.4,12.4.2,EN_EWT_RCYPCAP,"Electronic waste recycling, per capita (Kg)",8,Albania,E,G,KG,NaN,NaN,NaN,3.237495,4.242644,4.889079,5.103762,5.303011,5.477067,5.639709
1,12,12.4,12.4.2,EN_EWT_RCYPCAP,"Electronic waste recycling, per capita (Kg)",28,Antigua and Barbuda,E,G,KG,NaN,NaN,NaN,NaN,11.883926,11.755779,12.078921,12.385940,12.666956,12.948181
2,12,12.4,12.4.2,EN_EWT_RCYPCAP,"Electronic waste recycling, per capita (Kg)",32,Argentina,E,G,KG,NaN,NaN,NaN,0.251208,0.260772,0.269173,0.277348,0.285165,0.291858,0.297713
3,12,12.4,12.4.2,EN_EWT_RCYPCAP,"Electronic waste recycling, per capita (Kg)",51,Armenia,E,G,KG,NaN,NaN,NaN,NaN,0.003605,0.003817,0.004013,0.004208,0.004399,0.004565
4,12,12.4,12.4.2,EN_EWT_RCYPCAP,"Electronic waste recycling, per capita (Kg)",36,Australia,E,G,KG,NaN,NaN,1.790084,2.159105,1.822310,2.258636,2.288291,2.303972,2.315433,2.333367

In [6]:
# 4th CSV
e_recycling_total = pd.read_excel('data/EN_EWT_RCYV.xlsx')
e_recycling_total.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Units,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,12,12.4,12.4.2,EN_EWT_RCYV,Electronic waste recycling (Tonnes),8,Albania,E,G,TONNES,NaN,NaN,NaN,9401.0,12288.00,14132.00,14731.64,15294.78,15788.93,16247.51
1,12,12.4,12.4.2,EN_EWT_RCYV,Electronic waste recycling (Tonnes),28,Antigua and Barbuda,E,G,TONNES,NaN,NaN,NaN,NaN,1100.00,1100.00,1141.70,1181.93,1219.60,1257.46
2,12,12.4,12.4.2,EN_EWT_RCYV,Electronic waste recycling (Tonnes),32,Argentina,E,G,TONNES,NaN,NaN,NaN,10600.0,11118.67,11594.76,12066.97,12529.34,12947.14,13331.80
3,12,12.4,12.4.2,EN_EWT_RCYV,Electronic waste recycling (Tonnes),51,Armenia,E,G,TONNES,NaN,NaN,NaN,NaN,10.50,11.17,11.78,12.39,12.98,13.50
4,12,12.4,12.4.2,EN_EWT_RCYV,Electronic waste recycling (Tonnes),36,Australia,E,G,TONNES,NaN,NaN,41000.0,50209.8,43000.00,54054.81,55520.14,56642.27,57650.00,58808.31

## Hazardous Waste Datasets

In [7]:
# 5th CSV
haz_waste_GDP = pd.read_excel('data/EN_HAZ_GENGDP.xlsx')
haz_waste_GDP.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Units,...,2007,2008,2010,2011,2012,2013,2014,2015,2016,2017
0,12,12.4,12.4.2,EN_HAZ_GENGDP,"Hazardous waste generated, per unit of GDP (ki...",12,Algeria,C,G,KG_PER_CON_USD,...,0.002486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12,12.4,12.4.2,EN_HAZ_GENGDP,"Hazardous waste generated, per unit of GDP (ki...",20,Andorra,C,G,KG_PER_CON_USD,...,NaN,NaN,NaN,NaN,NaN,0.000358,0.000746,0.000636,0.000671,0.000524
2,12,12.4,12.4.2,EN_HAZ_GENGDP,"Hazardous waste generated, per unit of GDP (ki...",51,Armenia,C,G,KG_PER_CON_USD,...,0.039917,0.045049,0.051119,0.051932,0.049256,0.058707,0.056387,0.052597,0.058220,0.047789
3,12,12.4,12.4.2,EN_HAZ_GENGDP,"Hazardous waste generated, per unit of GDP (ki...",40,Austria,C,G,KG_PER_CON_USD,...,NaN,0.003598,0.004066,NaN,0.002839,NaN,0.003366,NaN,0.003235,NaN
4,12,12.4,12.4.2,EN_HAZ_GENGDP,"Hazardous waste generated, per unit of GDP (ki...",31,Azerbaijan,C,G,KG_PER_CON_USD,...,0.000277,0.000580,0.002917,0.003931,0.006152,0.003971,0.008694,0.004947,0.012296,0.005184

In [8]:
# 6th CSV
haz_waste_total = pd.read_excel('data/EN_HAZ_GENV.xlsx')
haz_waste_total.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Units,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,12,12.4,12.4.2,EN_HAZ_GENV,Hazardous waste generated (Tonnes),12,Algeria,C,G,TONNES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12,12.4,12.4.2,EN_HAZ_GENV,Hazardous waste generated (Tonnes),20,Andorra,C,G,TONNES,...,NaN,NaN,NaN,NaN,NaN,976.0000,2.081000e+03,1788.0000,1.923400e+03,1527.500
2,12,12.4,12.4.2,EN_HAZ_GENV,Hazardous waste generated (Tonnes),51,Armenia,C,G,TONNES,...,4.372585e+05,441023.5625,4.353978e+05,462895.8125,4.705057e+05,579049.8125,5.764194e+05,555076.5625,6.154706e+05,543232.125
3,12,12.4,12.4.2,EN_HAZ_GENV,Hazardous waste generated (Tonnes),40,Austria,C,G,TONNES,...,1.329984e+06,NaN,1.472864e+06,NaN,1.065888e+06,NaN,1.272288e+06,NaN,1.260953e+06,NaN
4,12,12.4,12.4.2,EN_HAZ_GENV,Hazardous waste generated (Tonnes),31,Azerbaijan,C,G,TONNES,...,2.427600e+04,131839.0000,1.399710e+05,185676.0000,2.969794e+05,202882.0000,4.566251e+05,262556.5000,6.326020e+05,265970.000

In [9]:
# 7th CSV
haz_waste_treated = pd.read_excel('data/EN_HAZ_TREATV.xlsx')
haz_waste_treated.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Type of waste treatment,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,12,12.4,12.4.2,EN_HAZ_TREATV,"Hazardous waste treated, by type of treatment ...",28,Antigua and Barbuda,C,G,LANDFIL,...,100.860001,52.959999,23.059999,157.220001,7.940000,7.1600,13.600,16.600000,NaN,NaN
1,12,12.4,12.4.2,EN_HAZ_TREATV,"Hazardous waste treated, by type of treatment ...",51,Armenia,C,G,INCINRT,...,1359.000000,456.000000,300.000000,12.000000,167.399994,17.0000,2379.000,289.700012,604.900024,582.799988
2,12,12.4,12.4.2,EN_HAZ_TREATV,"Hazardous waste treated, by type of treatment ...",51,Armenia,C,G,LANDFIL,...,433537.531250,438227.562500,432811.781250,457729.812500,460844.687500,574973.8125,571750.375,551020.062500,601917.375000,541012.375000
3,12,12.4,12.4.2,EN_HAZ_TREATV,"Hazardous waste treated, by type of treatment ...",51,Armenia,C,G,RECYCL,...,2362.000000,2340.000000,2286.000000,5154.000000,7983.000000,4059.0000,2290.000,3766.800049,12948.299805,1636.900024
4,12,12.4,12.4.2,EN_HAZ_TREATV,"Hazardous waste treated, by type of treatment ...",40,Austria,C,G,INCINRT,...,77201.000000,NaN,67983.000000,NaN,62905.000000,NaN,71327.000,NaN,NaN,NaN

## Domestic Material Consumption Datasets

In [10]:
# 8th CSV
dom_mat_consumption_pc = pd.read_excel('data/EN_MAT_DOMCMPC.xlsx')
dom_mat_consumption_pc.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Type of product,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,12,12.2,12.2.2,EN_MAT_DOMCMPC,"Domestic material consumption per capita, by t...",4,Afghanistan,E,G,BIM,...,1.72341,1.97509,1.93652,1.82431,1.90564,1.83294,1.82012,1.80205,1.78902,1.77893
1,12,12.2,12.2.2,EN_MAT_DOMCMPC,"Domestic material consumption per capita, by t...",4,Afghanistan,E,G,COL,...,0.01271,0.01785,0.02517,0.02440,0.02443,0.04246,0.04633,0.04798,0.04962,0.05124
2,12,12.2,12.2.2,EN_MAT_DOMCMPC,"Domestic material consumption per capita, by t...",4,Afghanistan,E,G,CPR,...,0.25770,0.39053,0.34634,0.26919,0.34736,0.34530,0.34594,0.34970,0.35385,0.35824
3,12,12.2,12.2.2,EN_MAT_DOMCMPC,"Domestic material consumption per capita, by t...",4,Afghanistan,E,G,CRO,...,0.35340,0.29748,0.39568,0.34340,0.30651,0.33876,0.34151,0.34352,0.34748,0.36444
4,12,12.2,12.2.2,EN_MAT_DOMCMPC,"Domestic material consumption per capita, by t...",4,Afghanistan,E,G,FEO,...,0.00145,0.00096,0.00258,0.00342,0.00336,0.00330,0.00324,0.00319,0.00315,0.00312

In [11]:
# 9th CSV
dom_mat_consumption_GDP = pd.read_excel('data/EN_MAT_DOMCMPG.xlsx')
dom_mat_consumption_GDP.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Type of product,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,12,12.2,12.2.2,EN_MAT_DOMCMPG,"Domestic material consumption per unit of GDP,...",4,Afghanistan,E,G,BIM,...,3.54062,3.55151,3.46922,3.10169,3.01790,2.81812,2.80302,2.91022,2.86592,2.85037
1,12,12.2,12.2.2,EN_MAT_DOMCMPG,"Domestic material consumption per unit of GDP,...",4,Afghanistan,E,G,COL,...,0.02612,0.03211,0.04509,0.04149,0.03869,0.06527,0.07135,0.07749,0.07949,0.08210
2,12,12.2,12.2.2,EN_MAT_DOMCMPG,"Domestic material consumption per unit of GDP,...",4,Afghanistan,E,G,CPR,...,0.52942,0.70223,0.62046,0.45768,0.55010,0.53089,0.53276,0.56475,0.56685,0.57400
3,12,12.2,12.2.2,EN_MAT_DOMCMPG,"Domestic material consumption per unit of GDP,...",4,Afghanistan,E,G,CRO,...,0.72603,0.53491,0.70885,0.58385,0.48541,0.52084,0.52593,0.55477,0.55665,0.58394
4,12,12.2,12.2.2,EN_MAT_DOMCMPG,"Domestic material consumption per unit of GDP,...",4,Afghanistan,E,G,FEO,...,0.00298,0.00173,0.00462,0.00581,0.00532,0.00507,0.00499,0.00516,0.00505,0.00500

In [12]:
# 10th CSV
dom_mat_consumption_total = pd.read_excel('data/EN_MAT_DOMCMPT.xlsx')
dom_mat_consumption_total.head()

,Goal,Target,Indicator,SeriesCode,SeriesDescription,GeoAreaCode,GeoAreaName,Nature,Reporting Type,Type of product,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,12,12.2,12.2.2,EN_MAT_DOMCMPT,"Domestic material consumption, by type of raw ...",4,Afghanistan,E,G,BIM,...,4.703888e+07,5.531095e+07,5.577784e+07,5.419777e+07,5.849743e+07,5.816242e+07,5.962340e+07,6.079494e+07,6.200024e+07,6.320554e+07
1,12,12.2,12.2.2,EN_MAT_DOMCMPT,"Domestic material consumption, by type of raw ...",4,Afghanistan,E,G,COL,...,3.470059e+05,5.000084e+05,7.250122e+05,7.250122e+05,7.500126e+05,1.347192e+06,1.517746e+06,1.618705e+06,1.719664e+06,1.820623e+06
2,12,12.2,12.2.2,EN_MAT_DOMCMPT,"Domestic material consumption, by type of raw ...",4,Afghanistan,E,G,CPR,...,7.033549e+06,1.093646e+07,9.975669e+06,7.997308e+06,1.066293e+07,1.095699e+07,1.133247e+07,1.179771e+07,1.226294e+07,1.272818e+07
3,12,12.2,12.2.2,EN_MAT_DOMCMPT,"Domestic material consumption, by type of raw ...",4,Afghanistan,E,G,CRO,...,9.645728e+06,8.330716e+06,1.139677e+07,1.020194e+07,9.408891e+06,1.074956e+07,1.118703e+07,1.158931e+07,1.204238e+07,1.294852e+07
4,12,12.2,12.2.2,EN_MAT_DOMCMPT,"Domestic material consumption, by type of raw ...",4,Afghanistan,E,G,FEO,...,3.955829e+04,2.690610e+04,7.431950e+04,1.015641e+05,1.031030e+05,1.046419e+05,1.061808e+05,1.077198e+05,1.092587e+05,1.107976e+05